CREATE TABLE public.etablissement_historique_src (
	siren varchar NULL,
	nic int4 NULL,
	siret varchar NULL,
	"dateFin" date NULL,
	"dateDebut" date NULL,
	"etatAdministratifEtablissement" varchar NULL,
	"changementEtatAdministratifEtablissement" bool NULL,
	"enseigne1Etablissement" varchar NULL,
	"enseigne2Etablissement" varchar NULL,
	"enseigne3Etablissement" varchar NULL,
	"changementEnseigneEtablissement" bool NULL,
	"denominationUsuelleEtablissement" varchar NULL,
	"changementDenominationUsuelleEtablissement" bool NULL,
	"activitePrincipaleEtablissement" varchar NULL,
	"nomenclatureActivitePrincipaleEtablissement" varchar NULL,
	"changementActivitePrincipaleEtablissement" bool NULL,
	"caractereEmployeurEtablissement" varchar NULL,
	"changementCaractereEmployeurEtablissement" bool NULL
);
