\echo "Date de début de traitement"
select now();
\echo "Création de la table etablissement "
CREATE UNLOGGED TABLE etablissement
(
    siren character varying(9) COLLATE pg_catalog."default",
    nic character varying(5) COLLATE pg_catalog."default",
    siret character varying(14) COLLATE pg_catalog."default" NOT NULL,
    "statutDiffusionEtablissement" character varying(1) COLLATE pg_catalog."default",
    "dateCreationEtablissement" date,
    "trancheEffectifsEtablissement" character varying(2) COLLATE pg_catalog."default",
    "anneeEffectifsEtablissement" integer,
    "activitePrincipaleRegistreMetiersEtablissement" character varying(6) COLLATE pg_catalog."default",
    "dateDernierTraitementEtablissement" timestamp without time zone,
    "etablissementSiege" boolean,
    "nombrePeriodesEtablissement" integer,
    "complementAdresseEtablissement" character varying(100) COLLATE pg_catalog."default",
    "numeroVoieEtablissement" character varying(9) COLLATE pg_catalog."default",
    "indiceRepetitionEtablissement" character varying(4) COLLATE pg_catalog."default",
    "dernierNumeroVoieEtablissement" character varying(9) COLLATE pg_catalog."default",
    "indiceRepetitionDernierNumeroVoieEtablissement" character varying(4) COLLATE pg_catalog."default",
    "typeVoieEtablissement" character varying(30) COLLATE pg_catalog."default",
    "libelleVoieEtablissement" character varying(100) COLLATE pg_catalog."default",
    "codePostalEtablissement" character varying(9) COLLATE pg_catalog."default",
    "libelleCommuneEtablissement" character varying(100) COLLATE pg_catalog."default",
    "libelleCommuneEtrangerEtablissement" character varying(100) COLLATE pg_catalog."default",
    "distributionSpecialeEtablissement" character varying(30) COLLATE pg_catalog."default",
    "codeCommuneEtablissement" character varying(10) COLLATE pg_catalog."default",
    "codeCedexEtablissement" character varying(30) COLLATE pg_catalog."default",
    "libelleCedexEtablissement" character varying(100) COLLATE pg_catalog."default",
    "codePaysEtrangerEtablissement" character varying(5) COLLATE pg_catalog."default",
    "libellePaysEtrangerEtablissement" character varying(100) COLLATE pg_catalog."default",
    "identifiantAdresseEtablissement" character varying(15) COLLATE pg_catalog."default",
    "coordonneeLambertAbscisseEtablissement" character varying(18) COLLATE pg_catalog."default",
    "coordonneeLambertOrdonneeEtablissement" character varying(18) COLLATE pg_catalog."default",
    "complementAdresse2Etablissement" character varying(100) COLLATE pg_catalog."default",
    "numeroVoie2Etablissement" character varying(30) COLLATE pg_catalog."default",
    "indiceRepetition2Etablissement" character varying(4) COLLATE pg_catalog."default",
    "typeVoie2Etablissement" character varying(30) COLLATE pg_catalog."default",
    "libelleVoie2Etablissement" character varying(100) COLLATE pg_catalog."default",
    "codePostal2Etablissement" character varying(9) COLLATE pg_catalog."default",
    "libelleCommune2Etablissement" character varying(100) COLLATE pg_catalog."default",
    "libelleCommuneEtranger2Etablissement" character varying(100) COLLATE pg_catalog."default",
    "distributionSpeciale2Etablissement" character varying(30) COLLATE pg_catalog."default",
    "codeCommune2Etablissement" character varying(5) COLLATE pg_catalog."default",
    "codeCedex2Etablissement" character varying(30) COLLATE pg_catalog."default",
    "libelleCedex2Etablissement" character varying(100) COLLATE pg_catalog."default",
    "codePaysEtranger2Etablissement" character varying(5) COLLATE pg_catalog."default",
    "libellePaysEtranger2Etablissement" character varying(100) COLLATE pg_catalog."default",
    "dateDebut" date,
    "etatAdministratifEtablissement" character varying(1) COLLATE pg_catalog."default",
    "enseigne1Etablissement" character varying(50) COLLATE pg_catalog."default",
    "enseigne2Etablissement" character varying(50) COLLATE pg_catalog."default",
    "enseigne3Etablissement" character varying(50) COLLATE pg_catalog."default",
    "denominationUsuelleEtablissement" character varying(100) COLLATE pg_catalog."default",
    "activitePrincipaleEtablissement" character varying(6) COLLATE pg_catalog."default",
    "nomenclatureActivitePrincipaleEtablissement" character varying(8) COLLATE pg_catalog."default",
    "caractereEmployeurEtablissement" character varying(1) COLLATE pg_catalog."default"
)
TABLESPACE pg_default;

\echo "Date de fin de traitement"
select now();