
CREATE UNLOGGED TABLE unite_legale_src (
   siren character varying(9) NOT NULL,
   "statutDiffusionUniteLegale" character varying(1),
   "unitePurgeeUniteLegale" boolean,
   "dateCreationUniteLegale" date,
   "sigleUniteLegale" character varying(20),
   "sexeUniteLegale" character varying(4),
   "prenom1UniteLegale" character varying(20),
   "prenom2UniteLegale" character varying(20),
   "prenom3UniteLegale" character varying(20),
   "prenom4UniteLegale" character varying(20),
   "prenomUsuelUniteLegale" character varying(20),
   "pseudonymeUniteLegale" character varying(100),
   "identifiantAssociationUniteLegale" character varying(10),
   "trancheEffectifsUniteLegale" character varying(2),
   "anneeEffectifsUniteLegale" integer,
   "dateDernierTraitementUniteLegale" timestamp without time zone,
   "nombrePeriodesUniteLegale" integer,
   "categorieEntreprise" character varying(3),
   "anneeCategorieEntreprise" integer,
   "dateDebut" date,
   "etatAdministratifUniteLegale" character varying(1),
   "nomUniteLegale" character varying(100),
   "nomUsageUniteLegale" character varying(100),
   "denominationUniteLegale" character varying(130),
   "denominationUsuelle1UniteLegale" character varying(70),
   "denominationUsuelle2UniteLegale" character varying(70),
   "denominationUsuelle3UniteLegale" character varying(70),
   "categorieJuridiqueUniteLegale" character varying(4),
   "activitePrincipaleUniteLegale" character varying(6),
   "nomenclatureActivitePrincipaleUniteLegale" character varying(8),
   "nicSiegeUniteLegale" character varying(5),
   "economieSocialeSolidaireUniteLegale" character varying(1),
   "societeMissionUniteLegale" character varying(1),
   "caractereEmployeurUniteLegale" boolean,
   "activitePrincipaleNAF25UniteLegale" character varying(6)
);
