worker_processes auto;

events {}

http {

  upstream backend {
    server backend:8000;
  }

  upstream superset {
    server superset:8088;
  }

  upstream keycloak {
    server keycloak:8080;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://backend;
    }

    location /superset/ {
      proxy_pass http://superset;
    }

    location /auth/ {
      proxy_pass http://keycloak;
    }
  }
}
